"""init

Revision ID: 80b5849c8f95
Revises: db2752e08230
Create Date: 2026-04-29 20:18:13.874439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b5849c8f95'
down_revision: Union[str, None] = 'db2752e08230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('wallets', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_unique_constraint(op.f('uq_wallets_user_id'), 'wallets', ['user_id'])
    op.create_foreign_key(op.f('fk_wallets_user_id_users'), 'wallets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_wallets_user_id_users'), 'wallets', type_='foreignkey')
    op.drop_constraint(op.f('uq_wallets_user_id'), 'wallets', type_='unique')
    op.drop_column('wallets', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
